servers:
  web:
    - 217.216.66.99
  jobs:
    hosts:
      - 217.216.66.99

env:
  clear:
    RAILS_ENV: production
    RAILS_LOG_LEVEL: fatal # suppress unstructured log lines
    BASE_URL: https://fizzy.rexielabs.com
    MAILER_FROM_ADDRESS: fizzy@rexielabs.com
    SMTP_ADDRESS: email-smtp.us-east-1.amazonaws.com
    SMTP_DOMAIN: rexielabs.com
    SMTP_PORT: 587
    MULTI_TENANT: true
    SOLID_QUEUE_IN_PUMA: true
    ACTIVE_STORAGE_SERVICE: s3
    S3_BUCKET: rexielabs-fizzy-production-activestorage
  secret:
    - SMTP_USERNAME
    - SMTP_PASSWORD
    - SECRET_KEY_BASE
    - VAPID_PUBLIC_KEY
    - VAPID_PRIVATE_KEY
    - S3_ACCESS_KEY_ID
    - S3_SECRET_ACCESS_KEY
    - SIGNAL_ID_SECRET
    - SENTRY_DSN
    - STRIPE_MONTHLY_V1_PRICE_ID
    - STRIPE_MONTHLY_EXTRA_STORAGE_V1_PRICE_ID
    - STRIPE_SECRET_KEY
    - STRIPE_WEBHOOK_SECRET
