service: fizzy
image: yorsant/rexie-labs/fizzy
asset_path: /rails/public/assets
hooks_path: <%= File.join(Gem::Specification.find_by_name("fizzy-saas").gem_dir, ".kamal", "hooks") %>
secrets_path: <%= File.join(Gem::Specification.find_by_name("fizzy-saas").gem_dir, ".kamal/secrets") %>

servers:
  jobs:
    cmd: bin/jobs

ssh:
  keys: [ "~/.ssh/contabo.pem" ]

proxy:
  ssl: true
  host: fizzy.rexielabs.com

volumes:
  - "fizzy_storage:/rails/storage"

registry:
  server: ghcr.io
  username: yorsant
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"
