# Name of this app
service: fizzy
image: yorsant/rexie-labs

#-- About your deployment --#
servers:
  web:
    - 217.216.66.99
  job:
    hosts:
      - 217.216.66.99
    cmd: bin/jobs

# How you connect to your server
ssh:
  keys: [ "~/.ssh/contabo.pem" ]

# Automatic SSL
proxy:
  ssl: true
  host: fizzy.rexielabs.com

# Your application configuration (secrets come from .kamal/secrets).
env:
  secret:
    - SECRET_KEY_BASE
    - VAPID_PUBLIC_KEY
    - VAPID_PRIVATE_KEY
    - SMTP_USERNAME
    - SMTP_PASSWORD
    - S3_ACCESS_KEY_ID
    - S3_SECRET_ACCESS_KEY
  clear:
    BASE_URL: https://fizzy.rexielabs.com
    MAILER_FROM_ADDRESS: fizzy@rexielabs.com
    SMTP_ADDRESS: email-smtp.us-east-1.amazonaws.com
    SMTP_DOMAIN: rexielabs.com
    SMTP_PORT: 587
    MULTI_TENANT: false
    SOLID_QUEUE_IN_PUMA: true
    ACTIVE_STORAGE_SERVICE: s3
    S3_BUCKET: rexielabs-fizzy-production-activestorage


#-- General configuration --#
registry:
  server: ghcr.io
  username: yorsant
  password:
    - KAMAL_REGISTRY_PASSWORD

# Handy aliases for interacting with your deployment. For eaxmple: `bin/kamal console` will connect to a
# Rails console in production.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

# Use a persistent storage volume for sqlite database files and local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
volumes:
  - "fizzy_storage:/rails/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: amd64
